#config_version=5
mode:
  start_events: ball_started
  priority: 100


show_player:
  mode_base_started:
    base_light_show:
      speed: 1
  base_start_single_player:
    base_single_player:
      key: base_score_loop
      #loops: -1
  base_start_multi_player_two:
   base_multi_player_two:
     key: base_score_loop
     #loops: -1
  base_start_multi_player_three:
   base_multi_player_three:
     key: base_score_loop
     #loops: -1
  base_start_multi_player_four:
   base_multi_player_four:
     key: base_score_loop
     #loops: -1

ball_saves:
  default:
    active_time: 10s
    hurry_up_time: 2s
    grace_period: 2s
    enable_events: mode_base_started
    timer_start_events: balldevice_bd_plunger_ball_eject_success
    auto_launch: true
    balls_to_save: 1
    debug: true

variable_player:
  s_right_inlane_active:
    score: 1000
  s_left_inlane_active:
    score: 1000
  s_right_outlane_active:
    score: 10000
  s_left_outlane_active:
    score: 10000
  s_left_slingshot_active:
    score: 500
  s_right_slingshot_active:
    score: 500
  s_pop_left_active:
    score: 500 
  s_pop_center_active:
    score: 500
  s_pop_right_active:
    score: 500
  s_rollover_mork_active:
    score: 1000
  s_rollover_gork_active:
    score: 1000
  s_upperscoop_active:
    score: 1000
  s_spinner_active:
    score: 100
  s_xenos_x_active:
    score: 100
  s_xenos_e_active:
    score: 100 
  s_xenos_n_active:
    score: 100
  s_xenos_o_active:
    score: 100  
  s_xenos_s_active:
    score: 100 
  s_kickback1_active:
    score: 100
  s_kickback2_active:
    score: 100
  s_disk_backtarget_active:
    score: 1000
  s_droptarget_active:
    score: 1000
  s_droptarget_lock_active:
    score: 1000
  s_center_spinner_active:
    score: 5000
  s_right_ramp_active:
    score: 1000
  s_scoop_active:
    score: 1000
  s_3bank_active:
    score: 1000



slide_player:
  player_added:
    new_player_slide:
      priority: 1000

slides:
  score_slide:
    widgets:
    - type: text
      text: (score)
      number_grouping: true
      min_digits: 2
      #style: dmd_big
      y: 18
    - type: text
      text: PLAYER (number)
      y: 0
      x: 10
      #style: dmd_med
      anchor_x: left
      anchor_y: bottom
    - type: text
      text: BALL (ball)
      y: 0
      x: right-10
      anchor_x: right
      anchor_y: bottom
      #style: dmd_med
  new_player_slide:
    expire: 1s
    widgets:
      - type: text
        text: PLAYER (num) ADDED
        #style: dmd_med

counters:
  warp_qualify_counter:
    count_events: s_3bank_active
    starting_count: 0
    count_interval: 1
    direction: up
    count_complete_value: 3 + (current_player.pv_warp_mode_counter * 2)
    events_when_complete: start_mode_warp
    reset_on_complete: true
    disable_on_complete: false
  necron_lock_qualifier:
    count_events: s_droptarget_down_active
    starting_count: pv_necron_lock_count
    count_interval : 1
    direction: up
    count_complete_value: 3
    events_when_complete: 
        - reset_necron_drop if pv_necron_lock_count < 3
        - increment_necron_lock
    disable_on_complete: false
  necron_lock_counter:
    count_events: increment_necron_lock
    starting_count: 0
    count_interval : 1
    direction: up
    count_complete_value: 1
    events_when_complete: start_necron_lock
    reset_on_complete: true
    disable_on_complete: true


event_player:
  mode_base_started: warp_traveler
  s_left_slingshot_active: sling_hit
  s_right_slingshot_active: sling_hit
  s_scoop_active: scoop_hit
  s_spinner_active: spinner_hit
  #player_added{num == 1}: base_sound_player_1
  player_added{num == 2}: base_sound_player_2
  player_added{num == 3}: base_sound_player_3
  player_added{num == 4}: base_sound_player_4
  player_added{game.num_players == 1}: base_start_single_player, base_sound_player_1
  player_added{game.num_players == 2}: base_start_multi_player_two
  player_added{game.num_players == 3}: base_start_multi_player_three
  player_added{game.num_players == 4}: base_start_multi_player_four
  mode_base_started{game.num_players == 1}: base_start_single_player
  mode_base_started{game.num_players == 2}: base_start_multi_player_two
  mode_base_started{game.num_players == 3}: base_start_multi_player_three
  mode_base_started{game.num_players == 4}: base_start_multi_player_four
  base_skillshot_should_start: skillshot_should_start
  ball_save_default_saving_ball:
    cmd_backbox_show_overlay:
      show_type: sweep_vertical
      color: "FF2000"
      speed: 1
      repeat: 0
      direction: up
  mode_bonus_will_start: stop_all_music
  
  

sound_player:
  warp_traveler: music_warp_traveler
  #mode_base_started{game.num_players == 1}: evenindeath 
  base_sound_player_1: evenindeath
  #base_start_single_player: player_ones
  base_sound_player_2: player_two
  base_sound_player_3: player_three
  base_sound_player_4: player_four
  left_sling_shot_hit: left_sling
  right_sling_shot_hit: right_sling
  upper_left_sling_shot_hit: mid_sling
  side_ramp_shot_hit: ramp_sound_4
  secret_passage_shot_hit: ramp_sound_2
  rollover_shot_hit: mini_loop
  scoop_shot_hit: scoop_eject
  thin_orange_shot_hit: energy_target
  shatz_shot_hit: zero_suit_target
  left_orbit_hit: left_orbit
  right_orbit_hit: right_orbit
  scoop_hit: sound_scoop
  sling_hit: sound_slinghit
  spinner_hit: lazgun
